FROM                eb-docker-study:base
MAINTAINER          zehye.01@gmail.com

ENV                 BUILD_MODE                  dev
ENV                 DJANGO_SETTINGS_MODULE      config.settings.${BUILD_MODE}

COPY                ./requirements.txt          /srv/
RUN                 pip install -r /srv/requirements.txt

COPY                .       /srv/project

# nginx설정파일들 복사 및 enabled로 링크
RUN             cp -f   /srv/project/.config/${BUILD_MODE}/nginx.conf \
                        /etc/nginx/nginx.conf && \
                cp -f   /srv/project/.config/${BUILD_MODE}/nginx_app.conf \
                        /etc/nginx/sites-available/ && \
                rm -rf  /etc/nginx/sites-enabled/* && \
                ln -sf  /etc/nginx/sites-available/nginx_app.conf \
                        /etc/nginx/sites-enabled/

# supervisor설정 복사
RUN             cp -f   /srv/project/.config/${BUILD_MODE}/supervisor.conf \
                        /etc/supervisor/conf.d/
# supervisord 실행
CMD             supervisord -n
